
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: schedulen
      POSTGRES_USER: schedulen
      POSTGRES_PASSWORD: schedulen_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U schedulen"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    image: ghcr.io/munennick/schedulen:latest
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://schedulen:schedulen_password@postgres:5432/schedulen
      NEXT_PUBLIC_BASE_URL: http://localhost:3000
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data: